### ISSUE TITLE
How to unsusbribe this image ?

### ISSUE THREAD

**Issue by punedhir** [bitnami/bitnami-docker-logstash-exporter#3]
**Description**
How could you unsubscribe to this image from Azure Portal? Subscribed the image but no longer required. Due to which the image is pushed/imported daily to ACR post deletion.

**Steps to reproduce the issue:**

1. Go to Azure Portal - Type Logstash Exporter packaged by Bitnami in Search Pane
2. You could subscribe this package but there is no option to unsusbscribe it.
3. Additionally, it keeps on pushing/importing the image to ACR which is no longer required.

**Describe the results you received:**

Image getting pushed/ imported daily to ACR which is no longer required.

**Describe the results you expected:**

Unsubscribe button or cancelling the image push to the ACR.

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @punedhir ,
I think that's something you will need to ask to the Azure support team
